//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime ContractDate { get; set; }
        public string BooksDelivery { get; set; }
        public int Discount { get; set; }
        public int TotalPrice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
